<?php

namespace Database\Seeders;


use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class SachSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */

    public function run(): void
    {
        // Tắt foreign key check để truncate không lỗi
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('sach')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $books = [
            [
                'maSach' => 'B001',
                'tenSach' => 'Nhà giả kim',
                'tacGia' => 'Paulo Coelho',
                'namXuatBan' => 1988,
                'soLuong' => 5,
                'idDanhMuc' => 1,
                'moTa' => 'Cuốn sách nổi tiếng về hành trình tìm kiếm ý nghĩa cuộc sống',
                'vitri' => 'Kệ A1',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B002',
                'tenSach' => 'Tôi thấy hoa vàng trên cỏ xanh',
                'tacGia' => 'Nguyễn Nhật Ánh',
                'namXuatBan' => 2010,
                'soLuong' => 8,
                'idDanhMuc' => 2,
                'moTa' => 'Câu chuyện tuổi thơ và tình bạn đẹp',
                'vitri' => 'Kệ B3',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B003',
                'tenSach' => 'Atomic Habits',
                'tacGia' => 'James Clear',
                'namXuatBan' => 2018,
                'soLuong' => 3,
                'idDanhMuc' => 3,
                'moTa' => 'Cách tạo thói quen tốt và loại bỏ thói quen xấu',
                'vitri' => 'Kệ C2',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B004',
                'tenSach' => 'Mắt biếc',
                'tacGia' => 'Nguyễn Nhật Ánh',
                'namXuatBan' => 1990,
                'soLuong' => 6,
                'idDanhMuc' => 2,
                'moTa' => 'Câu chuyện tình yêu lãng mạn và buồn',
                'vitri' => 'Kệ B1',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B005',
                'tenSach' => 'Dế mèn phiêu lưu ký',
                'tacGia' => 'Tô Hoài',
                'namXuatBan' => 1941,
                'soLuong' => 10,
                'idDanhMuc' => 4,
                'moTa' => 'Hành trình phiêu lưu của chú Dế Mèn',
                'vitri' => 'Kệ D4',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B006',
                'tenSach' => 'Sapiens',
                'tacGia' => 'Yuval Noah Harari',
                'namXuatBan' => 2011,
                'soLuong' => 7,
                'idDanhMuc' => 5,
                'moTa' => 'Lược sử loài người',
                'vitri' => 'Kệ E1',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B007',
                'tenSach' => 'Dế mèn phiêu lưu ký 2',
                'tacGia' => 'Tô Hoài',
                'namXuatBan' => 1945,
                'soLuong' => 4,
                'idDanhMuc' => 4,
                'moTa' => 'Tiếp nối hành trình phiêu lưu của chú Dế Mèn',
                'vitri' => 'Kệ D5',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B008',
                'tenSach' => 'Lịch sử Việt Nam',
                'tacGia' => 'Nguyễn Khắc Viện',
                'namXuatBan' => 1995,
                'soLuong' => 5,
                'idDanhMuc' => 6,
                'moTa' => 'Tổng quan về lịch sử Việt Nam',
                'vitri' => 'Kệ F1',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B009',
                'tenSach' => 'Phát triển bản thân 101',
                'tacGia' => 'Brian Tracy',
                'namXuatBan' => 2005,
                'soLuong' => 6,
                'idDanhMuc' => 3,
                'moTa' => 'Những kỹ năng cần thiết để phát triển bản thân',
                'vitri' => 'Kệ C3',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B010',
                'tenSach' => 'Thiếu nhi vui học',
                'tacGia' => 'Nhiều tác giả',
                'namXuatBan' => 2015,
                'soLuong' => 12,
                'idDanhMuc' => 4,
                'moTa' => 'Những câu chuyện hay cho thiếu nhi',
                'vitri' => 'Kệ D1',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'maSach' => 'B011',
                'tenSach' => 'Đắc nhân tâm',
                'tacGia' => 'Dale Carnegie',
                'namXuatBan' => 1936,
                'soLuong' => 7,
                'idDanhMuc' => 3,
                'moTa' => 'Nghệ thuật giao tiếp và thành công',
                'vitri' => 'Kệ C4',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B012',
                'tenSach' => 'Bí mật của tư duy triệu phú',
                'tacGia' => 'T. Harv Eker',
                'namXuatBan' => 2005,
                'soLuong' => 5,
                'idDanhMuc' => 3,
                'moTa' => 'Cách suy nghĩ để giàu có',
                'vitri' => 'Kệ C5',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B013',
                'tenSach' => 'Harry Potter và Hòn đá phù thủy',
                'tacGia' => 'J.K. Rowling',
                'namXuatBan' => 1997,
                'soLuong' => 8,
                'idDanhMuc' => 4,
                'moTa' => 'Khởi đầu của hành trình pháp thuật Harry Potter',
                'vitri' => 'Kệ D2',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B014',
                'tenSach' => 'Harry Potter và Phòng chứa bí mật',
                'tacGia' => 'J.K. Rowling',
                'namXuatBan' => 1998,
                'soLuong' => 7,
                'idDanhMuc' => 4,
                'moTa' => 'Phần 2 của bộ truyện Harry Potter',
                'vitri' => 'Kệ D3',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B015',
                'tenSach' => 'Chiến tranh và hòa bình',
                'tacGia' => 'Lev Tolstoy',
                'namXuatBan' => 1969,
                'soLuong' => 4,
                'idDanhMuc' => 1,
                'moTa' => 'Tiểu thuyết lịch sử kinh điển',
                'vitri' => 'Kệ A2',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B016',
                'tenSach' => 'Người giàu có nhất thành Babylon',
                'tacGia' => 'George S. Clason',
                'namXuatBan' => 1926,
                'soLuong' => 6,
                'idDanhMuc' => 3,
                'moTa' => 'Bí quyết quản lý tiền bạc và làm giàu',
                'vitri' => 'Kệ C6',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B017',
                'tenSach' => 'Tuổi thơ dữ dội',
                'tacGia' => 'Phùng Quán',
                'namXuatBan' => 1988,
                'soLuong' => 5,
                'idDanhMuc' => 2,
                'moTa' => 'Cuộc sống tuổi thơ trong chiến tranh',
                'vitri' => 'Kệ B4',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B018',
                'tenSach' => 'Chí Phèo',
                'tacGia' => 'Nam Cao',
                'namXuatBan' => 1941,
                'soLuong' => 8,
                'idDanhMuc' => 1,
                'moTa' => 'Tác phẩm phản ánh xã hội làng quê Việt Nam',
                'vitri' => 'Kệ A3',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B019',
                'tenSach' => 'Những tấm lòng cao cả',
                'tacGia' => 'Edmondo De Amicis',
                'namXuatBan' => 1986,
                'soLuong' => 5,
                'idDanhMuc' => 4,
                'moTa' => 'Những câu chuyện về lòng nhân hậu',
                'vitri' => 'Kệ D6',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'maSach' => 'B020',
                'tenSach' => 'Nhà giầu và túi rỗng',
                'tacGia' => 'Nguyễn Văn A',
                'namXuatBan' => 2020,
                'soLuong' => 10,
                'idDanhMuc' => 3,
                'moTa' => 'Cuốn sách về quản lý tài chính cá nhân',
                'vitri' => 'Kệ C7',
                'trangThai' => 'available',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('sach')->insert($books);
    }
}
